FROM golang:1.15-alpine AS go-builder

RUN apk add git gcc g++ make

WORKDIR $GOPATH/src/github.com/dwethmar/go-api

# We want to populate the module cache based on the go.{mod,sum} files.
COPY go.mod go.sum ./

RUN go mod verify 

COPY . .

# Build the Go app
RUN make buildArm

# Start fresh from a smaller image
FROM alpine:3.9 
RUN apk add ca-certificates

COPY --from=go-builder /go/src/github.com/dwethmar/go-api/server /app/

COPY ./scripts/migrations /app/

EXPOSE 8080

CMD ["/app/server"]
