version: "3.8"

services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile.raspbian
    environment:
      API_PQ_HOST: ${API_PQ_HOST}
      API_PG_PORT: ${API_PG_PORT}
      API_PQ_USER: ${API_PQ_USER}
      API_PQ_PASSWORD: ${API_PQ_PASSWORD}
      API_PQ_DB_NAME: ${API_PQ_DB_NAME}
      API_DRIVER_NAME: ${API_DRIVER_NAME}

    ports:
      - "8080:8080"
    restart: unless-stopped
    link:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${API_PQ_USER:-postgres}
      POSTGRES_PASSWORD: ${API_PQ_PASSWORD:-postgres}
      POSTGRES_DB: go-api
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./scripts/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
  
  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-postgres@localhost}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-postgres}
  #   volumes:
  #     - ./pgadmin4/servers.json:/pgadmin4/servers.json
  #   ports:
  #     - "${PGADMIN_PORT:-5050}:80"
  #   restart: unless-stopped
  #   links:
  #     - postgres

volumes:
  postgres:
